version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: full_db_postgres
    environment:
      - POSTGRES_USER=gusampaio
      - POSTGRES_PASSWORD=gusampaio_pass
      - POSTGRES_DB=hbday_db
      - DATABASE_HOST=localhost
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data

  app:
    container_name: hbday_app
    build: .
    ports:
      - 8080:8080
    restart: on-failure

volumes:
  database_postgres:


# Networks to be created to facilitate communication between containers
networks:
  fullstack:
  local:
    driver: bridge