apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend-chart.fullname" . }}
  labels:
    {{- include "backend-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "backend-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "backend-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: "test"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: POSTGRES_USER
            value: {{ .Values.env.POSTGRES_USER }}
          - name: POSTGRES_PASSWORD
            value: {{ .Values.env.POSTGRES_PASSWORD }}
          - name: POSTGRES_DB
            value: {{ .Values.env.POSTGRES_DB }}
          - name: DATABASE_HOST
            value: {{ .Values.env.DATABASE_HOST }}