apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ include "backend-chart.fullname" . }}
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /hello
            pathType: Prefix
            backend:
              service:
                name: {{ include "backend-chart.fullname" . }}-service
                port:
                  number:  {{ .Values.service.port }}